# To build and launch (first time):
#   $ docker-compose up -d
# To create new images (--no-cache) to force building from scratch:
#   $ docker-compose build
# To launch again (leave out -d for non daemon launch):
#   $ docker-compose up -d
# Short command for rebuilding and restarting
#   $ docker-compose up -d --build
# To stop containers:
#  $ docker-compose stop
# To clean up containers/images/networks:
#  $ docker system prune
networks:
  frontend:
    driver: bridge
  database:
    driver: bridge
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: "Dockerfile.nginx.webgme.org"
    restart: unless-stopped
    depends_on:
      - webgme-server
    volumes:
      - ~/dockershare/ssl_certs:/ssl_certs
      - ~/webgme.org/www/static:/static
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
  webgme-server:
    container_name: webgme
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - NODE_ENV=docker
    volumes:
      - ~/dockershare:/dockershare
    networks:
      - database
      - frontend
  mongo:
    container_name: mongo
    image: mongo:5
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ~/dockershare/db:/data/db
    networks:
      - database
