// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');


// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push('node_modules/premonition/src/plugins');
config.plugin.basePaths.push('node_modules/logic-gates/src/plugins');
config.plugin.basePaths.push('node_modules/petri-net/src/plugins');
config.plugin.basePaths.push('node_modules/finite-state-machine/src/plugins');
config.plugin.basePaths.push('node_modules/formula/src/plugins');
config.visualization.decoratorPaths.push('node_modules/petri-net/src/decorators');
config.visualization.decoratorPaths.push('node_modules/logic-gates/src/decorators');
config.visualization.decoratorPaths.push('node_modules/business-process-modeling/src/decorators');
config.seedProjects.basePaths.push('node_modules/premonition/src/seeds/premonition');
config.seedProjects.basePaths.push('node_modules/logic-gates/src/seeds/LogicGates');
config.seedProjects.basePaths.push('node_modules/petri-net/src/seeds/PetriNet');
config.seedProjects.basePaths.push('node_modules/finite-state-machine/src/seeds/FiniteStateMachine');
config.seedProjects.basePaths.push('node_modules/business-process-modeling/src/seeds/BusinessProcessModeling');


// Visualizer descriptors

// Add requirejs paths
config.requirejsPaths = {
  'BusinessProcessModelingDecorator': 'node_modules/business-process-modeling/src/decorators/BusinessProcessModelingDecorator',
  'LogicGatesDecorator': 'node_modules/logic-gates/src/decorators/LogicGatesDecorator',
  'PetriNetDecorator': 'node_modules/petri-net/src/decorators/PetriNetDecorator',
  'BusinessProcessModeling': 'node_modules/business-process-modeling/src/seeds/BusinessProcessModeling',
  'FiniteStateMachine': 'node_modules/finite-state-machine/src/seeds/FiniteStateMachine',
  'PetriNet': 'node_modules/petri-net/src/seeds/PetriNet',
  'LogicGates': 'node_modules/logic-gates/src/seeds/LogicGates',
  'premonition': 'node_modules/premonition/src/seeds/premonition',
  'Export2FORMULA': 'node_modules/formula/src/plugins/Export2FORMULA',
  'FSMImporter': 'node_modules/finite-state-machine/src/plugins/FSMImporter',
  'FSMCodeGenerator': 'node_modules/finite-state-machine/src/plugins/FSMCodeGenerator',
  'PetriNetExporter': 'node_modules/petri-net/src/plugins/PetriNetExporter',
  'LogicGatesExporter': 'node_modules/logic-gates/src/plugins/LogicGatesExporter',
  'PipelinePlugin': 'node_modules/premonition/src/plugins/PipelinePlugin'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/editor';
validateConfig(config);
module.exports = config;
